export const FoodData = [
  {
    id: 1,
    name: "Fresh Garden Salad",
    category: "Salad",
    price_range: "$ 8.9",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/salad1.png"),
    address: "123 Main Street, Cityville",
    phone: "+123-456-7890",
    description:
      "A refreshing blend of crisp lettuce, cherry tomatoes, cucumbers, and carrots, topped with your choice of dressing.",
  },
  {
    id: 2,
    name: "Mediterranean Chickpea Salad",
    category: "Salad",
    price_range: "$ 11",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/salad2.png"),
    address: "456 Elm Street, Townsville",
    phone: "+123-555-6789",
    description:
      "A flavorful combination of chickpeas, red onions, tomatoes, cucumbers, feta cheese, and olives, tossed in a tangy vinaigrette.",
  },
  {
    id: 3,
    name: "Grilled Chicken Caesar Salad",
    category: "Salad",
    price_range: "$ 9",
    rating: "⭐️⭐️⭐️⭐️",
    image: require("./assets/salad3.png"),
    address: "789 Oak Avenue, Villagetown",
    phone: "+123-777-1234",
    description:
      "Grilled chicken breast served on a bed of crisp romaine lettuce, tossed with Caesar dressing, croutons, and Parmesan cheese.",
  },
  {
    id: 4,
    name: "Avocado Caprese Salad",
    category: "Salad",
    price_range: "$ 12",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/salad4.png"),
    address: "789 Oak Avenue, Villagetown",
    phone: "+123-777-1234",
    description:
      "A colorful mix of ripe tomatoes, creamy avocado slices, fresh mozzarella cheese, basil leaves, and balsamic glaze.",
  },
  {
    id: 5,
    name: "Quinoa and Kale Salad",
    category: "Salad",
    price_range: "$ 10",
    rating: "⭐️⭐️⭐️⭐️",
    image: require("./assets/salad5.png"),
    address: "789 Oak Avenue, Villagetown",
    phone: "+123-777-1234",
    description:
      "A nutritious blend of quinoa, kale, cherry tomatoes, cucumbers, bell peppers, and avocado, tossed in a zesty lemon vinaigrette.",
  },
  {
    id: 24,
    name: "Cobb Salad",
    category: "Salad",
    price_range: "$ 12.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/salad6.png"),
    address: "456 Elm Street, Townsville",
    phone: "+123-555-6789",
    description:
      "A hearty salad featuring diced chicken, crispy bacon, hard-boiled eggs, tomatoes, avocado, and blue cheese crumbles.",
  },
  {
    id: 23,
    name: "Greek Salad",
    category: "Salad",
    price_range: "$ 10.99",
    rating: "⭐️⭐️⭐️",
    image: require("./assets/salad7.png"),
    address: "123 Main Street, Cityville",
    phone: "+123-456-7890",
    description:
      "A classic Greek salad with fresh lettuce, tomatoes, cucumbers, red onions, Kalamata olives, and feta cheese, tossed in a Greek vinaigrette.",
  },
  {
    id: 22,
    name: "Caesar Salad",
    category: "Salad",
    price_range: "$ 9.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/salad8.png"),
    address: "789 Oak Avenue, Villagetown",
    phone: "+123-777-1234",
    description:
      "Crisp romaine lettuce, crunchy croutons, and shredded Parmesan cheese, tossed in creamy Caesar dressing.",
  },
  {
    id: 6,
    name: "Margherita Pizza",
    category: "Pizza",
    price_range: "$ 10.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza1.png"),
    address: "123 Main Street, Cityville",
    phone: "+123-456-7890",
    description:
      "Classic Italian pizza topped with fresh tomatoes, mozzarella cheese, basil leaves, and a drizzle of olive oil.",
  },
  {
    id: 7,
    name: "Pepperoni Pizza",
    category: "Pizza",
    price_range: "$ 12.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza2.png"),
    address: "456 Elm Street, Townsville",
    phone: "+123-555-6789",
    description:
      "Classic favorite featuring tomato sauce, mozzarella cheese, and generous slices of spicy pepperoni.",
  },
  {
    id: 8,
    name: "BBQ Chicken Pizza",
    category: "Pizza",
    price_range: "$ 13.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza3.png"),
    address: "789 Oak Avenue, Villagetown",
    phone: "+123-777-1234",
    description:
      "Delicious pizza topped with tangy barbecue sauce, grilled chicken, red onions, and cilantro.",
  },
  {
    id: 9,
    name: "Vegetarian Pizza",
    category: "Pizza",
    price_range: "$ 11.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza4.png"),
    address: "123 Main Street, Cityville",
    phone: "+123-456-7890",
    description:
      "A delightful combination of fresh vegetables including bell peppers, onions, mushrooms, and olives.",
  },
  {
    id: 10,
    name: "Meat Lover's Pizza",
    category: "Pizza",
    price_range: "$ 14.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza5.png"),
    address: "456 Elm Street, Townsville",
    phone: "+123-555-6789",
    description:
      "Loaded with an assortment of meats including pepperoni, sausage, ham, bacon, and ground beef.",
  },
  {
    id: 11,
    name: "Hawaiian Pizza",
    category: "Pizza",
    price_range: "$ 12.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza6.png"),
    address: "789 Oak Avenue, Villagetown",
    phone: "+123-777-1234",
    description:
      "A tropical twist with pineapple, ham, and mozzarella cheese, perfect for those who love sweet and savory flavors.",
  },
  {
    id: 12,
    name: "Supreme Pizza",
    category: "Pizza",
    price_range: "$ 13.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza7.png"),
    address: "123 Main Street, Cityville",
    phone: "+123-456-7890",
    description:
      "Loaded with a variety of toppings including pepperoni, sausage, bell peppers, onions, olives, and mushrooms.",
  },
  {
    id: 13,
    name: "Buffalo Chicken Pizza",
    category: "Pizza",
    price_range: "$ 12.99",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    image: require("./assets/pizza8.png"),
    address: "456 Elm Street, Townsville",
    phone: "+123-555-6789",
    description:
      "Spicy buffalo sauce, grilled chicken, red onions, and a drizzle of ranch dressing, a perfect balance of heat and flavor.",
  },
];
